name: ffa_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas[version='>=1.3.*']
  - altair_viewer[version='>=0.4.*']
  - requests[version='>=2.24.0']
  - matplotlib[version='>=3.2.2']
  - python-graphviz[version='0.19']
  - altair
  - jinja2
  - graphviz
  - scikit-learn[version='>=1.0']
  - ipykernel
  - altair_saver
  - pip
  - docopt
  - dataframe_image
  - statsmodels
  - pandoc
  - lxml
  - pytest
